### PR TITLE
updating so able to remove categories in csv_importer [#92555138]

### PR DESCRIPTION
**Pull request by ilanaseid**
@niedfelj updated csv_importer so we can remove categories (for the subcategory updating project)

### CODE REVIEW

**Comment by niedfelj** [comment]
What is this related to?

**Comment by niedfelj** [comment]
Products get their categories from BP and are overwritten on sync...soooo they need to be updated in BP.

**Comment by ilanaseid** [comment]
hi Joel, for the BP categories, the API docs say you can create new and get all categories, but doesn't seem to have a way to delete by BP product. Does this mean the deletion needs to happen by hand on the app? https://www.brightpearl.com/developer/latest/product/brightpearl-category/post.html 

If so, propose we merge this so we can migrate to delete the Accessories, and Textile subcategories on launch so they don't show up on the grid and I'll work with Tayler and Jacob to make sure they remove manually from BP so it doesn't sync?

**Comment by niedfelj** [comment]
they update stuff by spreadsheet already in BP, and it should be coordinated with Jacob, whomever as BP needs to be the master.

**Pull request closed without merging**
